### ISSUE TITLE
Warren_G._Harding is misleading

### ISSUE THREAD

**Issue by tstaerk** [DavisNT/ExternalRedirect#4]
Hi,

it works!!! That feels so good that it works :)
However, I had to invest some debugging to make it work. You have an example on https://www.mediawiki.org/wiki/Extension:ExternalRedirect This example is 

$wgExternalRedirectPages = array(
    'Teapot_Dome_scandal',
    'Warren_G._Harding'
);

I concluded from this that I have to replace spaces in my title by underscores which is not true.

**Comment by DavisNT** [comment]
As far as I remember, latest MediaWiki version during development of this extension required spaces in page titles to be replaced with underscores. 
I will test with current version of MediaWiki.

On which MediaWiki version have you faced this issue?

P.S. I will also think about including page name and namespace in the error message.

**Comment by DavisNT** [comment]
~~As far as I remember, latest MediaWiki version during development of this extension required spaces in page titles to be replaced with underscores.~~ 
I will test with current version of MediaWiki.
I will also think about including page name and namespace in the error message.

On which MediaWiki version have you faced this issue?

P.S. `ExternalRedirect.php` does **not** need to be edited. However in `LocalSettings.php` extension configuration should be specified **after** the `require_once` line for that extension (I have fixed this in the extension page on mediawiki.org).

**Comment by tstaerk** [comment]
Thanks for the answer, sorry for the late reply. Indeed that could be the case:

MediaWiki | 1.34.2
PHP | 7.3.31-1~deb10u1 (fpm-fcgi)
MariaDB | 10.3.36-MariaDB-0+deb10u2

I think error messages are art, thanks for considering it!

**Comment by DavisNT** [comment]
Thank you very much, @tstaerk !
The [documentation](https://www.mediawiki.org/wiki/Extension:ExternalRedirect) is now fixed - you were right, the title does not need spaces to be replaced with underscores (for any MediaWiki version released since around initial release of this extension).

I have looked in MediaWiki source and `getPrefixedText()` [is returning spaces](https://github.com/wikimedia/mediawiki/blame/1.38.4/includes/Title.php#L1900) (instead of underscores) and [it has returned spaces](https://github.com/wikimedia/mediawiki/blame/0bdcf342fc26fcd66cf1b19884ca25cdaf857899/includes/Title.php#L1465) (instead of underscores) at least since year 2011. And this extension [has always used](https://github.com/DavisNT/ExternalRedirect/blob/26f3e1c6ee2f9284f0a923edd911e84eb0dfe782/ExternalRedirect.php#L60) `getPrefixedText()`.
